services:
  media-service:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: media-service:latest
    hostname: media-service.mediamaster.internal
    container_name: media-service.mediamaster.internal
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - mediamaster-internal-network

networks:
  mediamaster-internal-network:
    name: mediamaster-internal-network
